name: Prepare for release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: ${{ github.ref }}
          draft: 'false'
          prerelease: 'false'
